title: Valores Globales
menu:
  img: /u/base/logo.svg
footer:
  div: curve-side
  dots:
  - url: https://www.tiktok.com/@distrito41experience
  - url: https://www.instagram.com/distrito41_paintball_indoor/
  - url: https://www.facebook.com/distrito41elche/
  - url: https://www.tripadvisor.es/Attraction_Review-g661469-d10783920-Reviews-Distrito_41_Paintball_Indoor-Elche_Costa_Blanca_Province_of_Alicante_Valencian_C.html
    icon: brand:tripadvisor
  - url: https://www.yumping.com/multiaventura/distrito-41--e19734939
    icon: brand:yumping
